version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgis/postgis:12-2.5
    environment:
      - POSTGRES_USER=${DB_USER:-polytrip}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-polytrip}

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=polytrip.conf.docker
      - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@localhost
      - DB_USER=${DB_USER:-polytrip}
      - DB_PASSWORD=${DB_PASSWORD:-polytrip}
    ports:
      - 8000:8000
    depends_on:
      - db
