# Generated by Django 3.2.16 on 2023-01-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
        ("accounts", "0002_user_is_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="schools.school"),
        ),
    ]
