# Generated by Django 3.2.16 on 2023-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Team name"),
        ),
    ]
