# Generated by Django 3.2.16 on 2023-01-26 14:11

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import colorfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Unique identifier (UUID4)", verbose_name="Uuid"),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="School name")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=18, samples=None, verbose_name="School color"
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="School coordinates"),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["name"],
            },
        ),
    ]
