# Generated by Django 3.2.16 on 2023-01-27 18:36

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Unique identifier (UUID4)", verbose_name="Uuid"),
                ),
                ("trip", django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name="Trip")),
                (
                    "team",
                    models.OneToOneField(
                        limit_choices_to={"is_team": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["team"],
            },
        ),
    ]
