# Generated by Django 3.2.16 on 2023-01-28 14:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip",
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326, verbose_name="Trip"),
        ),
    ]
