# Generated by Django 3.2.16 on 2023-02-05 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Start date of the Polytrip event",
                        verbose_name="Start date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site configuration",
            },
        ),
    ]
