name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: polytrip
      POSTGRES_PASSWORD: polytrip
      POSTGRES_DB: polytrip
    services:
      postgres_main:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system requirements
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends libgdal-dev gdal-bin
      - name: Install requirements
        run: |
          pip install -r requirements/dev.txt codecov
      - name: Run tests
        env:
          SECRET_KEY: dummy
          DB_NAME: ${{ env.POSTGRES_DB }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          python src/manage.py collectstatic --noinput --link
          coverage run src/manage.py test src
      - name: Publish coverage report
        uses: codecov/codecov-action@v3
